# Generated by Django 4.2.6 on 2023-10-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
