# Generated by Django 4.2.6 on 2023-10-29 21:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_authorprofile_delete_commentreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='news', max_length=200),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
