# Generated by Django 4.2.6 on 2023-10-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_category_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
