# Generated by Django 4.2.6 on 2024-01-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_delete_authorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
