# Generated by Django 4.2.6 on 2024-01-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_article_created_at_remove_article_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
